swagger: '2.0'
info:
  title: Hub Search
  description: MCP Test Specification, YAML for streamable MCP support in Copilot Studio
  version: 1.0.0
host: labassist.pnnl.gov
basePath: /
schemes:
  - https
paths:
  /mcp:
    get:
      summary: Hub Search Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success